-- -----------------------------------------------------
-- SQL - DDL
-- -----------------------------------------------------



-- MySQL Script generated by MySQL Workbench
-- Wed Jun 21 00:42:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `CPF` VARCHAR(14) NOT NULL,
  `Nome` VARCHAR(50) NOT NULL,
  `Sexo` VARCHAR(1) NOT NULL,
  `Telefone` VARCHAR(13) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `data_Nasc` DATE NOT NULL,
  `Notas` INT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_Inicio` DATE NOT NULL,
  `Aluno_CPF` VARCHAR(14) NOT NULL,
  `descricao` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Turma_Aluno_idx` (`Aluno_CPF` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Turma_Aluno`
    FOREIGN KEY (`Aluno_CPF`)
    REFERENCES `mydb`.`Aluno` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Escola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Escola` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(13) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Turma_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Escola_Turma1_idx` (`Turma_id` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Escola_Turma1`
    FOREIGN KEY (`Turma_id`)
    REFERENCES `mydb`.`Turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `UF` VARCHAR(2) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `comp` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `Escola_ID` INT NOT NULL,
  INDEX `fk_Endereco_Escola1_idx` (`Escola_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Escola1`
    FOREIGN KEY (`Escola_ID`)
    REFERENCES `mydb`.`Escola` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Responsavel` (
  `CPF` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(70) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Aluno_CPF` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`CPF`),
  INDEX `fk_Responsavel_Aluno1_idx` (`Aluno_CPF` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Responsavel_Aluno1`
    FOREIGN KEY (`Aluno_CPF`)
    REFERENCES `mydb`.`Aluno` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conteudo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conteudo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(100) NULL,
  `Turma_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Conteudo_Turma1_idx` (`Turma_id` ASC) VISIBLE,
  CONSTRAINT `fk_Conteudo_Turma1`
    FOREIGN KEY (`Turma_id`)
    REFERENCES `mydb`.`Turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Modulo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Data_Inicio` DATE NOT NULL,
  `Data_Fim` DATE NOT NULL,
  `Conteudo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Modulo_Conteudo1_idx` (`Conteudo_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Modulo_Conteudo1`
    FOREIGN KEY (`Conteudo_id`)
    REFERENCES `mydb`.`Conteudo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prova` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(100) NULL,
  `Modulo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Prova_Modulo1_idx` (`Modulo_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Prova_Modulo1`
    FOREIGN KEY (`Modulo_id`)
    REFERENCES `mydb`.`Modulo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Questoes`
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Table `mydb`.`Questoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Questoes` (
   `Respostas` VARCHAR(1) NOT NULL,
   `id` INT NOT NULL AUTO_INCREMENT,
   `Enunciado` VARCHAR(300) NOT NULL,
   `Descricao` VARCHAR(100) NULL,
   `Prova_id` INT NOT NULL,
   PRIMARY KEY (`id`),
   INDEX `fk_Questoes_Prova1_idx` (`Prova_id` ASC) VISIBLE,
   UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
   CONSTRAINT `fk_Questoes_Prova1`
     FOREIGN KEY (`Prova_id`)
     REFERENCES `mydb`.`Prova` (`id`)
     ON DELETE NO ACTION
     ON UPDATE NO ACTION
) ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
